#!/usr/bin/env python3
"""
embed_binary.py  —  embed an arbitrary binary file as a C++ byte array.

Usage:
    python3 embed_binary.py <input_file> <output_cpp> <variable_name>

Generates a .cpp file that defines:
    extern "C" const unsigned char <variable_name>_data[];
    extern "C" const size_t        <variable_name>_size;
which can then be loaded at runtime (e.g. via newLibraryWithData for Metal).
"""

import sys

def embed(input_path, output_path, var_name):
    data = open(input_path, 'rb').read()
    with open(output_path, 'w') as f:
        f.write('// Auto-generated by embed_binary.py — do not edit\n')
        f.write('#include <stddef.h>\n')
        f.write('extern "C" {\n')
        # 'extern const' gives the symbols external linkage on C++ compilers
        # (plain 'const' at namespace scope is internal-linkage by default in C++).
        f.write('extern const unsigned char {}_data[] = {{'.format(var_name))
        # 16 bytes per line for readability
        for i, b in enumerate(data):
            if i % 16 == 0:
                f.write('\n  ')
            f.write('{},'.format(b))
        f.write('\n};\n')
        f.write('extern const size_t {}_size = sizeof({}_data);\n'.format(var_name, var_name))
        f.write('} // extern "C"\n')

if __name__ == '__main__':
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)
    embed(sys.argv[1], sys.argv[2], sys.argv[3])
