#!/usr/bin/env python3
"""
embed_model.py — macOS replacement for `ld -r -b binary`.

Embeds a .pt model file as a C++ byte array, creating the same symbol names
that GNU ld's `-b binary` would produce so that make_model_cpp.py works unchanged.

Usage:
    python3 embed_model.py <input.pt> <output.cpp> <stem>

Where <stem> is the filename stem (e.g. "all_default_to_default_1.3_1") used to
build the symbol name:  _binary_lib_models_<stem_underscored>_pt_start / _end
"""

import sys
from pathlib import Path

def embed(input_pt: str, output_cpp: str, stem: str) -> None:
    sym = '_binary_lib_models_' + stem.replace('.', '_') + '_pt'
    data = open(input_pt, 'rb').read()
    n = len(data)
    with open(output_cpp, 'w') as f:
        f.write('// Auto-generated by embed_model.py — do not edit\n')
        f.write('#include <stddef.h>\n')
        f.write('extern "C" {\n')
        f.write(f'char {sym}_start[] = {{')
        for i, b in enumerate(data):
            if i % 16 == 0:
                f.write('\n  ')
            f.write(f'(char){b},')
        f.write('\n};\n')
        # _end must point one-past the last byte of _start (same as GNU ld -b binary convention).
        # An empty array at a different address would give wrong pointer arithmetic in cnn_torch_scorer.cpp.
        f.write(f'char* {sym}_end = {sym}_start + {n};\n')
        f.write('} // extern "C"\n')

if __name__ == '__main__':
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)
    embed(sys.argv[1], sys.argv[2], sys.argv[3])
