/*
 * metal_context.mm  —  Objective-C++ implementation of MetalContext
 *
 * Must be compiled as Objective-C++ (.mm extension).
 * CMake target: compiled only when USE_METAL=ON (Apple Silicon).
 */

#include "metal_context.h"

#ifdef USE_METAL
#ifdef __APPLE__

#import <Metal/Metal.h>
#import <Foundation/Foundation.h>

#include <mutex>
#include <iostream>

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers: cast between opaque C++ handles and real ObjC types.
// The header exposes opaque pointers so it stays pure C++; here we bridge.
// ─────────────────────────────────────────────────────────────────────────────
static inline id<MTLDevice>       toDevice(MTLDeviceHandle h)       { return (__bridge id<MTLDevice>)h; }
static inline id<MTLCommandQueue> toQueue(MTLCommandQueueHandle h)  { return (__bridge id<MTLCommandQueue>)h; }
static inline id<MTLBuffer>       toBuffer(MTLBufferHandle h)       { return (__bridge id<MTLBuffer>)h; }

static inline MTLDeviceHandle       fromDevice(id<MTLDevice> d)       { return (__bridge MTLDeviceHandle)d; }
static inline MTLCommandQueueHandle fromQueue(id<MTLCommandQueue> q)  { return (__bridge MTLCommandQueueHandle)q; }
static inline MTLBufferHandle       fromBuffer(id<MTLBuffer> b)       { return (__bridge MTLBufferHandle)b; }

// ─────────────────────────────────────────────────────────────────────────────
// Embedded gnina_kernels.metallib (generated by embed_binary.py at build time)
// ─────────────────────────────────────────────────────────────────────────────
extern "C" {
    extern const unsigned char gnina_metallib_data[];
    extern const size_t        gnina_metallib_size;
}

// ─────────────────────────────────────────────────────────────────────────────
// Singleton storage
// ─────────────────────────────────────────────────────────────────────────────
static MetalContext* g_instance = nullptr;
static std::once_flag g_init_flag;

// Thread-local command queue (one per CPU thread, lazy-initialised).
static thread_local id<MTLCommandQueue> tl_queue = nil;

// ARC-managed retain of the per-thread queue so it isn't released while the
// thread is alive.
static thread_local __strong id<MTLCommandQueue> tl_queue_owner = nil;

// ─────────────────────────────────────────────────────────────────────────────
// MetalContext implementation
// ─────────────────────────────────────────────────────────────────────────────

// Cast between opaque handle and ObjC PSO type.
static inline id<MTLComputePipelineState> toPSO(MTLComputePipelineStateHandle h) {
    return (__bridge id<MTLComputePipelineState>)h;
}

MetalContext::MetalContext() : _library(nullptr) {
    id<MTLDevice> dev = MTLCreateSystemDefaultDevice();
    if (!dev) {
        std::cerr << "[gnina] FATAL: Metal is not supported on this device.\n";
        std::abort();
    }
    _device = fromDevice(dev);

    // Retain the device so ARC doesn't release it.
    CFRetain((__bridge CFTypeRef)dev);

    std::cout << "[gnina] Metal device: "
              << [dev.name UTF8String]
              << " (recommendedMaxWorkingSetSize = "
              << dev.recommendedMaxWorkingSetSize / (1024*1024) << " MB)\n";

    _loadLibrary();
}

MetalContext::~MetalContext() {
    if (_library) {
        CFRelease((CFTypeRef)_library);
        _library = nullptr;
    }
    if (_device) {
        CFRelease((__bridge CFTypeRef)toDevice(_device));
        _device = nullptr;
    }
}

void MetalContext::_loadLibrary() {
    id<MTLDevice> dev = toDevice(_device);
    NSError* error = nil;

    // Wrap the static metallib bytes in NSData (no-copy, no-free) and pass to
    // newLibraryWithData:.  NSData is toll-free bridged to dispatch_data_t.
    NSData* libData = [NSData dataWithBytesNoCopy:(void*)gnina_metallib_data
                                           length:gnina_metallib_size
                                     freeWhenDone:NO];

    id<MTLLibrary> lib = [dev newLibraryWithData:(dispatch_data_t)libData error:&error];
    if (!lib) {
        std::cerr << "[gnina] FATAL: Failed to load Metal library: "
                  << [[error localizedDescription] UTF8String] << "\n";
        std::abort();
    }

    // Transfer ownership so ARC doesn't release the library while we hold it.
    _library = (void*)CFBridgingRetain(lib);
    std::cout << "[gnina] Metal compute library loaded ("
              << gnina_metallib_size << " bytes)\n";
}

MetalContext& MetalContext::instance() {
    std::call_once(g_init_flag, []() {
        g_instance = new MetalContext();
    });
    return *g_instance;
}

MTLCommandQueueHandle MetalContext::commandQueue() {
    if (!tl_queue) {
        id<MTLDevice> dev = toDevice(_device);
        tl_queue_owner = [dev newCommandQueue];
        tl_queue = tl_queue_owner;
        if (!tl_queue) {
            std::cerr << "[gnina] FATAL: Failed to create MTLCommandQueue.\n";
            std::abort();
        }
    }
    return fromQueue(tl_queue);
}

MTLBufferHandle MetalContext::newBuffer(size_t bytes) {
    id<MTLDevice> dev = toDevice(_device);
    // MTLStorageModeShared: the buffer's contents() pointer is valid for both
    // CPU and GPU accesses. On Apple Silicon this is true zero-copy —
    // there is only one physical copy of the data.
    id<MTLBuffer> buf = [dev newBufferWithLength:bytes
                                        options:MTLResourceStorageModeShared];
    if (!buf) {
        std::cerr << "[gnina] FATAL: Failed to allocate Metal buffer of "
                  << bytes << " bytes.\n";
        std::abort();
    }
    // Transfer ownership to the caller (they are responsible for calling
    // releaseBuffer() when done).
    return fromBuffer((__bridge_retained id<MTLBuffer>)buf);
}

void MetalContext::releaseBuffer(MTLBufferHandle buf) {
    if (buf) {
        // Balance the __bridge_retained in newBuffer().
        CFRelease((__bridge CFTypeRef)toBuffer(buf));
    }
}

void* MetalContext::bufferContents(MTLBufferHandle buf) {
    return [toBuffer(buf) contents];
}

void MetalContext::synchronize() {
    // Create an empty command buffer, commit it, and wait.
    // Used to ensure all previously submitted GPU work on this thread's queue
    // has completed before the CPU reads GPU-written data.
    id<MTLCommandQueue> queue = toQueue(commandQueue());
    id<MTLCommandBuffer> cb = [queue commandBuffer];
    [cb commit];
    [cb waitUntilCompleted];
}

bool MetalContext::available() {
    return MTLCreateSystemDefaultDevice() != nil;
}

// ─────────────────────────────────────────────────────────────────────────────
// Compute pipeline and dispatch
// ─────────────────────────────────────────────────────────────────────────────

MTLComputePipelineStateHandle MetalContext::makePipeline(const char* functionName) {
    if (!_library) {
        std::cerr << "[gnina] FATAL: makePipeline called before library loaded.\n";
        std::abort();
    }
    id<MTLLibrary> lib = (__bridge id<MTLLibrary>)_library;
    id<MTLDevice>  dev = toDevice(_device);

    NSString* name = [NSString stringWithUTF8String:functionName];
    id<MTLFunction> fn = [lib newFunctionWithName:name];
    if (!fn) {
        std::cerr << "[gnina] FATAL: Metal function not found: " << functionName << "\n";
        std::abort();
    }

    NSError* error = nil;
    id<MTLComputePipelineState> pso =
        [dev newComputePipelineStateWithFunction:fn error:&error];
    if (!pso) {
        std::cerr << "[gnina] FATAL: Failed to create pipeline for '"
                  << functionName << "': "
                  << [[error localizedDescription] UTF8String] << "\n";
        std::abort();
    }

    // Transfer ownership to the caller.
    return (MTLComputePipelineStateHandle)CFBridgingRetain(pso);
}

void MetalContext::releasePipeline(MTLComputePipelineStateHandle pso) {
    if (pso) CFRelease((CFTypeRef)pso);
}

void MetalContext::dispatch1D(MTLComputePipelineStateHandle psoH,
                              const MetalArg* args,
                              int nArgs,
                              size_t threadCount)
{
    if (threadCount == 0) return;

    id<MTLComputePipelineState> pso = toPSO(psoH);
    id<MTLCommandQueue>         q   = toQueue(commandQueue());
    id<MTLCommandBuffer>        cb  = [q commandBuffer];
    id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];

    [enc setComputePipelineState:pso];

    for (int i = 0; i < nArgs; ++i) {
        if (args[i].is_buffer) {
            [enc setBuffer:toBuffer(args[i].buf)
                   offset:args[i].offset
                  atIndex:i];
        } else {
            [enc setBytes:args[i].bytes
                   length:args[i].length
                  atIndex:i];
        }
    }

    // dispatchThreads (Metal 2, available on all Apple Silicon) lets the GPU
    // handle boundary threads without needing a threadgroup-aligned count.
    NSUInteger tgSize = pso.maxTotalThreadsPerThreadgroup;
    if (tgSize > 256) tgSize = 256;
    [enc dispatchThreads:MTLSizeMake(threadCount, 1, 1)
        threadsPerThreadgroup:MTLSizeMake(tgSize, 1, 1)];

    [enc endEncoding];
    [cb commit];
    [cb waitUntilCompleted];
}

// ─────────────────────────────────────────────────────────────────────────────
// Free helper
// ─────────────────────────────────────────────────────────────────────────────
MTLCommandQueueHandle metalThreadCommandQueue() {
    return MetalContext::instance().commandQueue();
}

#endif // __APPLE__
#endif // USE_METAL
