// These variables are autogenerated into version.cpp and compiled
// into the library by the version.cmake script

extern const char* GIT_TAG;
extern const char* GIT_REV;
extern const char* GIT_BRANCH;


